# Generated by Django 5.0.6 on 2024-05-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('availableUnits', models.IntegerField(max_length=50)),
                ('wifi', models.BooleanField(default=True)),
                ('laundry', models.BooleanField(default=True)),
            ],
        ),
    ]
